services:
  thor-solo:
    image: vechain/thor:latest
    hostname: thor-solo
    container_name: thor-solo
    user: root
    environment:
      - DOCKER=1
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "apk update && apk upgrade && apk add curl && thor solo --on-demand --data-dir /data/thor --api-addr 0.0.0.0:8669 --api-cors '*' --api-backtrace-limit -1 --verbosity 4",
      ]
    ports:
      - "8669:8669"
    healthcheck:
      test: curl --fail 0.0.0.0:8669/blocks/0 || exit 1
      interval: "2s"
      retries: 30

  inspector:
    image: ghcr.io/vechain/inspector-app:V1.1.0
    container_name: inspector
    environment:
      NODE_ENV: production
      VUE_APP_SOLO_URL: http://localhost:8669
    volumes:
      # This allows us to pre-populate the contracts. Your local path should contain a file called `contracts.json`
      - "./packages/contracts/output:/usr/share/nginx/html/abis"
    ports:
      - 3001:80

  insight:
    image: ghcr.io/vechain/insight-app:master
    hostname: insight
    container_name: insight
    environment:
      - VUE_APP_SOLO_URL=http://localhost:8669
    ports:
      - 3002:80
